spring:
  jpa:
   database: POSTGRESQL
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true
   format_sql: true
   open-in-view: false
   properties:
     hibernate:
       format_sql: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/classifier?currentSchema=classifier
    driver-class-name: org.postgresql.Driver