spring:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    username: postgres
    password: pass
    url: jdbc:postgresql://localhost:5432/users?currentSchema=security
    driver-class-name: org.postgresql.Driver
  mvc:
    format:
      date: iso
      date-time: iso
project:
  details:
    mailPattern: ^[a-zA-Z0-9]{2,10}$
    nickPattern: ^[a-zA-Z0-9]{2,10}$
    passwordPattern: ^[a-zA-Z0-9]{2,10}$

    mailErrorMessage: Некорректные символы
    nickErrorMessage: Некорректные символы
    passwordErrorMessage: Некорректные символы




